server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

url:
  mocky:
    io: http://www.mocky.io/v2/5e5ec624310000b738afd85a

springfox:
  documentation:
    swagger:
      v2:
        path: /api.json
api-credito:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:*}
  api-info:
    title: ${API_TITLE:API REST}
    description: ${API_DESCRIPTION:Documentação da API de Crédito}
    version: ${API_VERSION:1.0.0}
    base-package: br.com.money.credito.controller